cmd/auth-rest/go.mod, cmd/auth-rest/go.sum, cmd/auth-rest/main.go, cmd/auth-rest/startcmd/start.go, cmd/auth-rest/startcmd/start_test.go, test/bdd/dockerutil/compose.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/common/common_steps.go
Logging level can now be set from command line or changed on-the-fly via the REST API.
=> feat: Configurable logging level

cmd/auth-rest/go.sum, cmd/auth-rest/startcmd/start.go, cmd/auth-rest/startcmd/start_test.go, go.mod, go.sum, test/bdd/fixtures/auth-rest/docker-compose.yml
=> feat: Storage provider command line flags

cmd/auth-rest/startcmd/start.go, pkg/restapi/controller_test.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go
=> fix: Separate providers for transient and persistent storage

.gitignore, scripts/check_unit.sh
=> chore: fix codecov

cmd/auth-rest/go.sum, cmd/auth-vue/src/pages/SelectProvider.vue, go.mod, go.sum, pkg/restapi/common/store/cookie/api.go, pkg/restapi/common/store/cookie/mock.go, pkg/restapi/common/store/cookie/store.go, pkg/restapi/operation/models.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go
=> refactor: use cookies

cmd/auth-rest/go.mod, cmd/auth-rest/go.sum, cmd/auth-rest/startcmd/start.go, cmd/auth-rest/startcmd/start_test.go, cmd/auth-rest/startcmd/storage.go, pkg/restapi/operation/operations.go, test/bdd/fixtures/auth-rest/docker-compose.yml, test/bdd/fixtures/auth-rest/mysql-config/mysql_config.sql
=> feat: mysql storage

cmd/auth-vue/src/pages/SelectProvider.vue
Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>
=> refactor: Add mock bank login button and remove other OIDC provider

Makefile, cmd/auth-rest/startcmd/start.go, cmd/auth-vue/package-lock.json, go.mod, go.sum, images/auth-rest/Dockerfile, pkg/restapi/controller_test.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go
=> fix: serve UI + oidc provider retries

cmd/auth-vue/public/index.html
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
=> fix: add referrer meta

test/bdd/pkg/context/context.go, test/bdd/pkg/login/mock_wallet.go, test/bdd/pkg/login/steps.go
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
=> test: store access token in bddtest ctx

pkg/restapi/common/hydra/client.go, pkg/restapi/common/hydra/client_test.go, pkg/restapi/operation/dependencies.go, pkg/restapi/operation/models.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, test/bdd/bddtests_test.go, test/bdd/features/bootstrap_data.feature, test/bdd/fixtures/auth-rest/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/bootstrap/steps.go, test/bdd/pkg/login/mock_wallet.go, test/bdd/pkg/login/steps.go
Also, refactored GET /bootstrap to implement oauth2 authz
=> feat: POST /bootstrap

.gitignore, cmd/auth-rest/startcmd/start.go, cmd/auth-rest/startcmd/start_test.go, scripts/generate_test_keys.sh, test/bdd/fixtures/auth-rest/docker-compose.yml
=> chore: #65 configure cookie auth and enc keys

cmd/auth-rest/go.mod, cmd/auth-rest/startcmd/parameters.go, cmd/auth-rest/startcmd/start.go, cmd/auth-rest/startcmd/start_test.go, pkg/restapi/controller_test.go, pkg/restapi/operation/dependencies.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, test/bdd/fixtures/auth-rest/docker-compose.yml, test/bdd/fixtures/auth-rest/oidc-config/providers.yaml, test/bdd/pkg/login/steps.go
=> feat: #61 support multiple OIDC providers

cmd/auth-vue/src/pages/SelectProvider.vue, test/bdd/fixtures/auth-rest/oidc-config/providers.yaml, test/bdd/pkg/login/steps.go
=> fix: align provider ID b/w frontend and backend config

pkg/restapi/operation/models.go
- Updated to be consistent with post bootstrap req
=> refactor: Fetch Bootstrap Response json key (entries -> data)

cmd/auth-vue/public/index.html, cmd/auth-vue/src/pages/SelectProvider.vue, cmd/auth-vue/src/pages/layout/Nav.vue
Signed-off-by: serena.hacker <Serena.Hacker@securekey.com>
=> fix: improve hub-auth ui for demo

ci/version_var.sh
=> chore: bump version to 0.1.6

Makefile, ci/azure-pipelines.yml, ci/version_var.sh, images/auth-rest/Dockerfile, test/bdd/fixtures/auth-rest/.env
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> ci: migrate to ghcr

ci/version_var.sh
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: rename docker image to hub-auth

cmd/auth-rest/go.mod, cmd/auth-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum, test/bdd/mock/loginconsent/go.mod, test/bdd/mock/loginconsent/go.sum
=> chore: update latest edge-core including AFG update

cmd/auth-rest/go.mod, cmd/auth-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum, test/bdd/mock/loginconsent/go.mod, test/bdd/mock/loginconsent/go.sum
=> chore: update to latest dependency

cmd/auth-rest/go.mod, cmd/auth-rest/go.sum
Updated MySQL storage provider implementation fixes the issue.
=> fix: keys not storing correctly

cmd/auth-rest/go.mod, cmd/auth-rest/go.sum
=> chore: Update aries-framework-go-ext storage commit versions

ci/version_var.sh
Closes #98
Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>
=> chore: complete Release v0.1.6

test/bdd/go.mod
=> chore: update hub-auth rev for external references to hub-auth test/bdd

cmd/auth-rest/startcmd/start.go, cmd/auth-rest/startcmd/start_test.go
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
=> fix: Make TLS optional

go.sum, pkg/restapi/controller_test.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go
=> fix: remove oidc provider validation during startup

cmd/auth-rest/startcmd/parameters.go, cmd/auth-rest/startcmd/start.go, go.sum, pkg/restapi/operation/models.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, test/bdd/fixtures/auth-rest/oidc-config/providers.yaml
=> feat: Fetch Auth Providers API

cmd/auth-vue/package.json, cmd/auth-vue/src/pages/SelectProvider.vue
Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>
=> feat: Add Dynamic auth provider UI

pkg/restapi/operation/operations.go
=> fix: update provider id

cmd/auth-rest/startcmd/start.go, pkg/restapi/operation/models.go
…for edge-agent integration
closes #132
Signed-off-by: talwinder kaur <talwinder.kaur@securekey.com>
=> fix: Oidc provider image loading issue and new provider field access for edge-agent integration

pkg/restapi/operation/operations.go
Signed-off-by: talwinder kaur <talwinder.kaur@securekey.com>
=> fix: Missing signuptest and signintext in the provider response

pkg/restapi/operation/operations.go
Signed-off-by: talwinder kaur <talwinder.kaur@securekey.com>
=> feat: Add provider to the hydra auth link

test/bdd/pkg/context/context.go
Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>
=> feat: add the possibility to create bdd context with out CA certs path

Makefile, ci/azure-pipelines.yml, cmd/auth-rest/go.mod, docs/build.md, go.mod, test/bdd/go.mod, test/bdd/mock/loginconsent/go.mod
=> chore: golang v1.17 update

.github/workflows/build.yml
=> test: add missing host name

README.md
=> ci: add github-actions status badge

ci/version_var.sh
=> chore: v0.1.8 release complete

.github/dependabot.yml
Fixes #187
Signed-off-by: Anton Biriukov <anton.biriukov@securekey.com>
=> feat: added dependabot config file

.gitignore, Makefile, component/gnap/as/client.go, component/gnap/as/client_test.go, component/gnap/rs/client.go, component/gnap/rs/client_test.go, component/gnap/testdata/scripts/generate_test_keys.sh, scripts/check_unit.sh, spi/gnap/api.go, spi/gnap/go.mod, spi/gnap/models.go
=> chore: introduce gnap client interface

.github/workflows/build.yml, cmd/auth-vue/package.json, cmd/auth-vue/src/App.vue, cmd/auth-vue/src/components/TheFooter.vue, cmd/auth-vue/src/components/TheToastNotification.vue, cmd/auth-vue/src/views/SignIn.vue, cmd/auth-vue/src/views/SignUp.vue, cmd/auth-vue/tailwind.config.mjs, scripts/check_lint.sh
Signed-off-by: Anton Biriukov <anton.biriukov@securekey.com>
=> feat: updated lint target to include frontend

.github/workflows/build.yml, cmd/auth-rest/startcmd/parameters.go, cmd/auth-rest/startcmd/start.go, docs/build.md, pkg/gnap/interact/redirect/interact.go, pkg/restapi/gnap/operations.go, pkg/restapi/gnap/operations_test.go, scripts/generate_test_keys.sh, test/bdd/fixtures/auth-rest/docker-compose.yml, test/bdd/pkg/gnap/steps.go
- Add interact handler API
- Build redirect interact handler url
part of #159 
=> feat: Interact handler

cmd/auth-rest/startcmd/start.go, pkg/gnap/authhandler/auth_handler.go, pkg/gnap/authhandler/auth_handler_test.go, pkg/gnap/session/session_manager.go, pkg/gnap/session/session_manager_test.go, pkg/internal/common/mockstorage/storage.go, pkg/restapi/controller.go, pkg/restapi/controller_test.go, pkg/restapi/gnap/operations.go, pkg/restapi/gnap/operations_test.go
=> feat: session manager using storage api for persistence

cmd/auth-rest/startcmd/parameters.go, cmd/auth-rest/startcmd/start.go, pkg/restapi/common/oidc/models.go, pkg/restapi/controller_test.go, pkg/restapi/gnap/dependencies.go, pkg/restapi/gnap/models.go, pkg/restapi/gnap/operations.go, pkg/restapi/gnap/operations_test.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go
Add auth provider and login handler API (copied most of the code from existing handlers to customize for gnap)
part of #208 
=> feat: [gnap] auth provider list and login handler API

cmd/auth-rest/startcmd/parameters.go, cmd/auth-rest/startcmd/start.go, pkg/gnap/accesspolicy/access_policy.go, pkg/gnap/accesspolicy/access_policy_test.go, pkg/gnap/accesspolicy/config.go, pkg/gnap/api/api.go, pkg/gnap/authhandler/auth_handler.go, pkg/gnap/authhandler/auth_handler_test.go, pkg/gnap/session/session_manager.go, pkg/gnap/session/session_manager_test.go, pkg/restapi/controller_test.go, pkg/restapi/gnap/operations.go, pkg/restapi/gnap/operations_test.go
=> feat: gnap server access policy logic

cmd/auth-rest/startcmd/start.go, pkg/restapi/controller_test.go, pkg/restapi/gnap/models.go, pkg/restapi/gnap/operations.go, pkg/restapi/gnap/operations_test.go
- add odicCallback handler
- remove dependencies on cookies
- refactor test based on above changes
part of #208 
=> feat: [gnap] oidc callback handler

cmd/auth-rest/startcmd/start.go, cmd/auth-vue/src/views/ProviderPopup.vue, cmd/auth-vue/src/views/SignIn.vue, cmd/auth-vue/src/views/SignUp.vue, pkg/restapi/gnap/operations.go, test/bdd/fixtures/auth-rest/hydra-config/thirdparty_hydra_configure.sh, test/bdd/pkg/gnap/steps.go
=> feat: [gnap] integrate oidc with frontend

cmd/auth-rest/startcmd/start.go, pkg/gnap/accesspolicy/access_policy.go, pkg/gnap/accesspolicy/access_policy_test.go, pkg/gnap/accesspolicy/config.go, pkg/gnap/api/api.go, pkg/gnap/authhandler/auth_handler.go, pkg/gnap/authhandler/auth_handler_test.go, pkg/gnap/authhandler/helpers.go, pkg/gnap/interact/redirect/interact.go, pkg/internal/common/mockinteract/interact.go, pkg/restapi/gnap/operations.go, pkg/restapi/gnap/operations_test.go, test/bdd/fixtures/auth-rest/docker-compose.yml, test/bdd/fixtures/auth-rest/gnap-config/access_policy.json, test/bdd/pkg/gnap/steps.go
=> feat: gnap interact integration

cmd/auth-vue/src/views/ProviderPopup.vue, cmd/auth-vue/src/views/SignUp.vue, pkg/restapi/gnap/operations.go, test/bdd/pkg/gnap/steps.go
=> fix: pass gnap interact transaction ID through login redirects

cmd/auth-vue/src/router/routes.js, cmd/auth-vue/src/views/SignIn.vue
=> fix: pass GNAP txnID properly through both signup and signin pages

cmd/auth-rest/startcmd/parameters.go, cmd/auth-rest/startcmd/start.go, pkg/gnap/authhandler/auth_handler.go, pkg/gnap/authhandler/auth_handler_test.go, pkg/restapi/gnap/operations.go
=> feat: add gnap-dev-mode option that disables http-signature verification

spi/gnap/internal/jwksignature/ecdsa.go, spi/gnap/internal/jwksignature/ecdsa_test.go, spi/gnap/internal/jwksignature/jwksignature_test.go
=> feat: add multi ecdsa key types

pkg/gnap/authhandler/auth_handler.go, pkg/gnap/interact/redirect/interact.go
=> fix: interact request-url was missing from interaction hash

spi/gnap/models.go
=> feat: gnap response models for subject data

pkg/gnap/accesspolicy/access_policy.go, pkg/gnap/accesspolicy/access_policy_test.go, pkg/gnap/api/api.go, pkg/gnap/authhandler/auth_handler.go, pkg/gnap/authhandler/auth_handler_test.go, pkg/gnap/session/session_manager.go, pkg/gnap/session/session_manager_test.go
=> feat: gnap server returns granted access tokens when re-requested

pkg/restapi/common/common.go, pkg/restapi/controller.go, pkg/restapi/gnap/operations.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, test/bdd/features/bootstrap_data_gnap.feature, test/bdd/pkg/bootstrap/steps.go, test/bdd/pkg/login/mock_wallet.go, test/bdd/pkg/login/steps.go
=> feat: allow bootstrap APIs to use GNAP tokens for auth

Makefile, cmd/auth-rest/startcmd/start.go, cmd/auth-rest/static/gnapRedirect.html, images/auth-rest/Dockerfile, pkg/restapi/gnap/operations.go, pkg/restapi/gnap/operations_test.go, test/bdd/pkg/gnap/steps.go
=> feat: GNAP flow closes popup window before wallet redirect

cmd/auth-rest/startcmd/start.go
Signed-off-by: Andrii Holovko <andriy.holovko@gmail.com>
=> fix: cors for gnap

spi/gnap/proof/httpsig/signer.go, spi/gnap/proof/httpsig/verifier.go
=> fix: http signature should sign @method and @target-uri instead of @request-target

cmd/auth-vue/src/views/SignIn.vue, cmd/auth-vue/src/views/SignUp.vue
Fixes #267
Signed-off-by: Anton Biriukov <anton.biriukov@avast.com>
=> fix: pass txnID in query between sign in/sign up pages

pkg/restapi/gnap/operations.go
closes #270 
Signed-off-by: Rolson Quadras <rolson.quadras@avast.com>
=> fix: [gnap] add callbackURL in authorization call

pkg/restapi/gnap/operations.go
=> chore: debug logging for gnap auth request URL
